# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: frgm-linux
  hooks:
    pre: packr2
    post: packr2 clean
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  ldflags:
    - -s -w -X github.com/k1LoW/frgm.version={{.Version}} -X github.com/k1LoW/frgm.commit={{.FullCommit}} -X github.com/k1LoW/frgm.date={{.Date}} -X github.com/k1LoW/frgm/version.Version={{.Version}}
-
  id: frgm-darwin
  hooks:
    pre: packr2
    post: packr2 clean
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  ldflags:
    - -s -w -X github.com/k1LoW/frgm.version={{.Version}} -X github.com/k1LoW/frgm.commit={{.FullCommit}} -X github.com/k1LoW/frgm.date={{.Date}} -X github.com/k1LoW/frgm/version.Version={{.Version}}
archives:
-
  id: frgm-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
-
  name: frgm
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/frgm
  description: frgm is a command snippets (fragments) manager.
  install: |
    system './frgm', 'completion', 'bash', '--out', 'frgm.bash'
    system './frgm', 'completion', 'zsh', '--out', 'frgm.zsh'
    bin.install 'frgm'
    bash_completion.install 'frgm.bash' => 'frgm'
    zsh_completion.install 'frgm.zsh' => '_frgm'
nfpms:
  -
    id: frgm-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - frgm-linux
    homepage: https://github.com/k1LoW/frgm
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: frgm is a command snippets (fragments) manager.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
