before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: frgm-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  ldflags:
    - -s -w -X github.com/k1LoW/frgm.version={{.Version}} -X github.com/k1LoW/frgm.commit={{.FullCommit}} -X github.com/k1LoW/frgm.date={{.Date}} -X github.com/k1LoW/frgm/version.Version={{.Version}}
-
  id: frgm-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/frgm.version={{.Version}} -X github.com/k1LoW/frgm.commit={{.FullCommit}} -X github.com/k1LoW/frgm.date={{.Date}} -X github.com/k1LoW/frgm/version.Version={{.Version}}
archives:
-
  id: frgm-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
  rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
nfpms:
  -
    id: frgm-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - frgm-linux
    homepage: https://github.com/k1LoW/frgm
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: frgm is a meta snippet (fragment) manager.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
